#!/usr/bin/env bash
lsmod|grep asus_nb_wmi &> /dev/null
if [ $? -eq 0 ]; then
    printf "Reloading asus_nb_wmi module..."
    rmmod asus_nb_wmi && modprobe asus_nb_wmi
else
    printf "asus_nb_wmi module is not loaded!"
fi
