#!/usr/bin/env bash
MODULE=asus_nb_wmi
lsmod|grep $MODULE &> /dev/null
if [ $? -eq 0 ]; then
    modprobe -r -v $MODULE
    sleep 3s
    modprobe -v $MODULE
    modprobe -v btusb
else
    printf "$MODULE module is not loaded!"
fi
